`timescale 1ns / 1ps

//////////////////////////////////////////////////////////////////////////////////
// Module Name: half_sine_table
// Description: This module contains a lookup table for a half sine wave.
//              The table is parameterized by size and bit resolution.
//
// Autogenerated from generate_modules_sine.py
//////////////////////////////////////////////////////////////////////////////////

module half_sine_table #(
    parameter SINE_SIZE = 12,
    parameter TABLE_SIZE = 268,
    parameter TABLE_REG_SIZE = 9
) (
    input  wire [TABLE_REG_SIZE-1:0] addr,       // Address to access the sine value
    output reg  [SINE_SIZE-1:0]      data,       // Sine value at the given address
    output wire [TABLE_REG_SIZE-1:0] table_size  // Maximum valid address (TABLE_SIZE - 1)
);

    // Internal memory array for the half sine wave lookup table
    reg [SINE_SIZE-1:0] sine_wave [0:TABLE_SIZE-1];

    // Constant assignment for table_size
    assign table_size = TABLE_SIZE - 1;
    // Initialise the lookup table with the sine values
    initial begin
        table_size = TABLE_SIZE-1;
        sine_wave[0] = 0;
        sine_wave[1] = 0;
        sine_wave[2] = 1;
        sine_wave[3] = 1;
        sine_wave[4] = 2;
        sine_wave[5] = 4;
        sine_wave[6] = 5;
        sine_wave[7] = 7;
        sine_wave[8] = 9;
        sine_wave[9] = 11;
        sine_wave[10] = 14;
        sine_wave[11] = 17;
        sine_wave[12] = 20;
        sine_wave[13] = 24;
        sine_wave[14] = 28;
        sine_wave[15] = 32;
        sine_wave[16] = 36;
        sine_wave[17] = 41;
        sine_wave[18] = 45;
        sine_wave[19] = 51;
        sine_wave[20] = 56;
        sine_wave[21] = 62;
        sine_wave[22] = 68;
        sine_wave[23] = 74;
        sine_wave[24] = 80;
        sine_wave[25] = 87;
        sine_wave[26] = 94;
        sine_wave[27] = 102;
        sine_wave[28] = 109;
        sine_wave[29] = 117;
        sine_wave[30] = 125;
        sine_wave[31] = 134;
        sine_wave[32] = 142;
        sine_wave[33] = 151;
        sine_wave[34] = 160;
        sine_wave[35] = 170;
        sine_wave[36] = 180;
        sine_wave[37] = 190;
        sine_wave[38] = 200;
        sine_wave[39] = 210;
        sine_wave[40] = 221;
        sine_wave[41] = 232;
        sine_wave[42] = 243;
        sine_wave[43] = 255;
        sine_wave[44] = 266;
        sine_wave[45] = 278;
        sine_wave[46] = 291;
        sine_wave[47] = 303;
        sine_wave[48] = 316;
        sine_wave[49] = 329;
        sine_wave[50] = 342;
        sine_wave[51] = 355;
        sine_wave[52] = 369;
        sine_wave[53] = 383;
        sine_wave[54] = 397;
        sine_wave[55] = 411;
        sine_wave[56] = 426;
        sine_wave[57] = 440;
        sine_wave[58] = 455;
        sine_wave[59] = 470;
        sine_wave[60] = 486;
        sine_wave[61] = 502;
        sine_wave[62] = 517;
        sine_wave[63] = 533;
        sine_wave[64] = 550;
        sine_wave[65] = 566;
        sine_wave[66] = 583;
        sine_wave[67] = 600;
        sine_wave[68] = 617;
        sine_wave[69] = 634;
        sine_wave[70] = 651;
        sine_wave[71] = 669;
        sine_wave[72] = 687;
        sine_wave[73] = 705;
        sine_wave[74] = 723;
        sine_wave[75] = 742;
        sine_wave[76] = 760;
        sine_wave[77] = 779;
        sine_wave[78] = 798;
        sine_wave[79] = 817;
        sine_wave[80] = 836;
        sine_wave[81] = 856;
        sine_wave[82] = 875;
        sine_wave[83] = 895;
        sine_wave[84] = 915;
        sine_wave[85] = 935;
        sine_wave[86] = 955;
        sine_wave[87] = 976;
        sine_wave[88] = 996;
        sine_wave[89] = 1017;
        sine_wave[90] = 1038;
        sine_wave[91] = 1059;
        sine_wave[92] = 1080;
        sine_wave[93] = 1101;
        sine_wave[94] = 1122;
        sine_wave[95] = 1144;
        sine_wave[96] = 1165;
        sine_wave[97] = 1187;
        sine_wave[98] = 1209;
        sine_wave[99] = 1231;
        sine_wave[100] = 1253;
        sine_wave[101] = 1275;
        sine_wave[102] = 1297;
        sine_wave[103] = 1320;
        sine_wave[104] = 1342;
        sine_wave[105] = 1365;
        sine_wave[106] = 1387;
        sine_wave[107] = 1410;
        sine_wave[108] = 1433;
        sine_wave[109] = 1456;
        sine_wave[110] = 1479;
        sine_wave[111] = 1502;
        sine_wave[112] = 1525;
        sine_wave[113] = 1549;
        sine_wave[114] = 1572;
        sine_wave[115] = 1595;
        sine_wave[116] = 1619;
        sine_wave[117] = 1642;
        sine_wave[118] = 1666;
        sine_wave[119] = 1689;
        sine_wave[120] = 1713;
        sine_wave[121] = 1737;
        sine_wave[122] = 1760;
        sine_wave[123] = 1784;
        sine_wave[124] = 1808;
        sine_wave[125] = 1832;
        sine_wave[126] = 1856;
        sine_wave[127] = 1880;
        sine_wave[128] = 1904;
        sine_wave[129] = 1928;
        sine_wave[130] = 1952;
        sine_wave[131] = 1976;
        sine_wave[132] = 2000;
        sine_wave[133] = 2023;
        sine_wave[134] = 2048;
        sine_wave[135] = 2072;
        sine_wave[136] = 2095;
        sine_wave[137] = 2119;
        sine_wave[138] = 2143;
        sine_wave[139] = 2167;
        sine_wave[140] = 2191;
        sine_wave[141] = 2215;
        sine_wave[142] = 2239;
        sine_wave[143] = 2263;
        sine_wave[144] = 2287;
        sine_wave[145] = 2311;
        sine_wave[146] = 2335;
        sine_wave[147] = 2358;
        sine_wave[148] = 2382;
        sine_wave[149] = 2406;
        sine_wave[150] = 2429;
        sine_wave[151] = 2453;
        sine_wave[152] = 2476;
        sine_wave[153] = 2500;
        sine_wave[154] = 2523;
        sine_wave[155] = 2546;
        sine_wave[156] = 2570;
        sine_wave[157] = 2593;
        sine_wave[158] = 2616;
        sine_wave[159] = 2639;
        sine_wave[160] = 2662;
        sine_wave[161] = 2685;
        sine_wave[162] = 2708;
        sine_wave[163] = 2730;
        sine_wave[164] = 2753;
        sine_wave[165] = 2775;
        sine_wave[166] = 2798;
        sine_wave[167] = 2820;
        sine_wave[168] = 2842;
        sine_wave[169] = 2864;
        sine_wave[170] = 2886;
        sine_wave[171] = 2908;
        sine_wave[172] = 2930;
        sine_wave[173] = 2951;
        sine_wave[174] = 2973;
        sine_wave[175] = 2994;
        sine_wave[176] = 3015;
        sine_wave[177] = 3036;
        sine_wave[178] = 3057;
        sine_wave[179] = 3078;
        sine_wave[180] = 3099;
        sine_wave[181] = 3119;
        sine_wave[182] = 3140;
        sine_wave[183] = 3160;
        sine_wave[184] = 3180;
        sine_wave[185] = 3200;
        sine_wave[186] = 3220;
        sine_wave[187] = 3239;
        sine_wave[188] = 3259;
        sine_wave[189] = 3278;
        sine_wave[190] = 3297;
        sine_wave[191] = 3316;
        sine_wave[192] = 3335;
        sine_wave[193] = 3353;
        sine_wave[194] = 3372;
        sine_wave[195] = 3390;
        sine_wave[196] = 3408;
        sine_wave[197] = 3426;
        sine_wave[198] = 3444;
        sine_wave[199] = 3461;
        sine_wave[200] = 3478;
        sine_wave[201] = 3495;
        sine_wave[202] = 3512;
        sine_wave[203] = 3529;
        sine_wave[204] = 3545;
        sine_wave[205] = 3562;
        sine_wave[206] = 3578;
        sine_wave[207] = 3593;
        sine_wave[208] = 3609;
        sine_wave[209] = 3625;
        sine_wave[210] = 3640;
        sine_wave[211] = 3655;
        sine_wave[212] = 3669;
        sine_wave[213] = 3684;
        sine_wave[214] = 3698;
        sine_wave[215] = 3712;
        sine_wave[216] = 3726;
        sine_wave[217] = 3740;
        sine_wave[218] = 3753;
        sine_wave[219] = 3766;
        sine_wave[220] = 3779;
        sine_wave[221] = 3792;
        sine_wave[222] = 3804;
        sine_wave[223] = 3817;
        sine_wave[224] = 3829;
        sine_wave[225] = 3840;
        sine_wave[226] = 3852;
        sine_wave[227] = 3863;
        sine_wave[228] = 3874;
        sine_wave[229] = 3885;
        sine_wave[230] = 3895;
        sine_wave[231] = 3905;
        sine_wave[232] = 3915;
        sine_wave[233] = 3925;
        sine_wave[234] = 3935;
        sine_wave[235] = 3944;
        sine_wave[236] = 3953;
        sine_wave[237] = 3961;
        sine_wave[238] = 3970;
        sine_wave[239] = 3978;
        sine_wave[240] = 3986;
        sine_wave[241] = 3993;
        sine_wave[242] = 4001;
        sine_wave[243] = 4008;
        sine_wave[244] = 4015;
        sine_wave[245] = 4021;
        sine_wave[246] = 4027;
        sine_wave[247] = 4033;
        sine_wave[248] = 4039;
        sine_wave[249] = 4044;
        sine_wave[250] = 4050;
        sine_wave[251] = 4054;
        sine_wave[252] = 4059;
        sine_wave[253] = 4063;
        sine_wave[254] = 4067;
        sine_wave[255] = 4071;
        sine_wave[256] = 4075;
        sine_wave[257] = 4078;
        sine_wave[258] = 4081;
        sine_wave[259] = 4084;
        sine_wave[260] = 4086;
        sine_wave[261] = 4088;
        sine_wave[262] = 4090;
        sine_wave[263] = 4091;
        sine_wave[264] = 4093;
        sine_wave[265] = 4094;
        sine_wave[266] = 4094;
        sine_wave[267] = 4095;
    end

    // Immediately output the sine value corresponding to the input address
    always @(*) begin
        data = sine_wave[addr];
    end

endmodule
